[build]
  command = "pip install -r requirements.txt && python migrate_db.py"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  directory = "."
  node_bundler = "esbuild"

[[functions]]
  path = "app.py"
  included_files = ["**/*.py", "**/*.html", "**/*.css", "**/*.js", "**/*.db", "requirements.txt", "templates/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
