services:
  - type: web
    name: committee-management-izun
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python migrate_db.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001
