services:
  - type: web
    name: committee-management-izun
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: FLASK_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/data/committee_system.db
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
