from .auth_routes import auth_bp
from .api_routes import api_bp
from .admin_routes import admin_bp
from .committee_routes import committee_bp
from .event_routes import event_bp
from .main_routes import main_bp
from .migration_routes import migration_bp
from .auto_schedule_routes import auto_schedule_bp
from .committee_type_routes import committee_type_bp
from .user_routes import user_bp
from .settings_routes import settings_bp
from .recycle_bin_routes import recycle_bin_bp
from .calendar_routes import calendar_bp
